---
title: "AM01 Final Project Group 4"
author: "Study Group 4 - Harsh Tripathi, Nikolaos Panayotou, Wei Guo, Xenia Huber, Xinyue Zhang"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---

```{r, setup, echo=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```

```{r load-libraries, echo=FALSE}
library(googlesheets4)
library(tidyverse)
library(janitor) 
library(skimr)
library(countrycode) # to clean up country names
library(broom)
library(car)
library(ggfortify)
library(stringr)
library(mosaic)
library(ggthemes)
library(GGally)
library(readxl)
library(here)
library(tidyquant)
library(infer)
library(openintro)
```


```{r load_data}
# use googlesheets4 to get data
# url <- "https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/edit?resourcekey#gid=1625408792"
# googlesheets4::gs4_auth() # google sheets authorisation

# load "Ask a A Manager 2021 Survey" googlesheet
# https://www.askamanager.org/
# ask_a_manager_2021 <- googlesheets4::read_sheet(url) %>% 
#   janitor::clean_names()

# if googlesheets is now working, read local copy
ask_a_manager_2021 <- read_csv(here::here("data", "ask_a_manager_2021.csv")) %>% 
  janitor::clean_names()
  

skimr::skim(ask_a_manager_2021)
```


```{r data_cleaning}
#data cleaning
ask_a_manager_2021_new <- ask_a_manager_2021 %>% 
  rename(age=how_old_are_you,overall_experience=overall_years_of_professional_experience,
         field_experience=years_of_experience_in_field,education_level=highest_level_of_education_completed) %>% 
  select(-timestamp,-additional_context_on_job_title ,-additional_context_on_income,-other_monetary_comp,-currency_other) %>% 
  mutate(age=factor(age,levels=c("under 18","18-24","25-34","35-44","45-54","55-64","65 or over"),
                    labels =c("under 18","18-24","25-34","35-44","45-54","55-64","65 or over") ,ordered = TRUE),
         overall_experience=factor(overall_experience,levels=c("1 year or less","2 - 4 years","5-7 years","8 - 10 years",
                                                               "11 - 20 years","21 - 30 years","31 - 40 years","41 years or more"),
                    labels =c("less than 1 year","2-4 years","5-7 years","8-10 years",
                              "11-20 years","21-30 years","31-40 years","41 years or more") ,ordered = TRUE),
         field_experience=factor(field_experience,levels=c("1 year or less","2 - 4 years","5-7 years","8 - 10 years","11 - 20 years","21 - 30 years","31 - 40 years","41 years or more"),
                      labels =c("less than 1 year","2-4 years","5-7 years","8-10 years",
                                             "11-20 years","21-30 years","31-40 years","41 years or more") ,ordered = TRUE),
         education_level=factor(education_level,levels=c("High School","Some college","College degree",
                                                         "Master's degree","PhD","Professional degree (MD, JD, etc.)"),
                                labels =c("High School","Some college","College degree",
                                          "Master's degree","PhD","Professional degree") ,ordered = TRUE),
         gender=case_when(gender=="Other or prefer not to answer"|gender=="Prefer not to answer"|is.na(gender)~"Don't know or NA",
                          TRUE~gender),state=ifelse(str_detect(state,",")|is.na(state),"NA",state))
#sort out country
# First we need to convert country name to iso3c
ask_a_manager_2021_new$iso3c <-countrycode(
  ask_a_manager_2021_new$country,
  origin = "country.name", destination = "iso3c")
# then change it back to country name
ask_a_manager_2021_new$country <-countrycode(
  ask_a_manager_2021_new$iso3c,
  origin = "iso3c", destination = "country.name")



industry_list<-ask_a_manager_2021_new %>% 
        group_by(industry) %>% 
        count(sort=TRUE) %>% 
        filter(n > 100) %>% 
        select(industry) %>% pull()
ask_a_manager_2021_new<-ask_a_manager_2021_new %>% 
     filter(industry %in% industry_list)

race_list<-ask_a_manager_2021_new %>% 
  group_by(race) %>% 
  count(sort=TRUE) %>% 
  filter(!is.na(race),n>100) %>% 
  select(race) %>% pull()
ask_a_manager_2021_new<-ask_a_manager_2021_new %>% 
  filter(race %in% race_list)

```

```{r}
skim(ask_a_manager_2021_new)
```

```{r cleaned_data}
#drop_na
ask_a_manager_2021_cleaned<-
  ask_a_manager_2021_new %>%  drop_na()
#filter
ask_a_manager_2021_cleaned<-
  ask_a_manager_2021_cleaned %>% 
  filter(annual_salary>10000&annual_salary<1000000)

skim(ask_a_manager_2021_cleaned)
```

```{r }
# problems need to be solved
# How is salary distributed?
ggplot(ask_a_manager_2021_cleaned, aes(x=annual_salary))+
  geom_boxplot()

ggplot(ask_a_manager_2021_cleaned, aes(x=annual_salary))+
  stat_ecdf()
```


```{r }
# problems need to be solved
# what about log(salary)? 
ggplot(ask_a_manager_2021_cleaned, aes(x=log(annual_salary)))+
  geom_density()


ggplot(ask_a_manager_2021_cleaned, aes(x=log(annual_salary)))+
  stat_ecdf()

# Which one (salary vs. log(salary)) is better to use in a regression model? Why?
```



```{r }
# age distribution in the survey
ask_a_manager_2021_cleaned %>% 
  count(age) %>% 
  ggplot(aes(x=age,y=n,fill=age)) +
  geom_col()+
  labs(x="Age group", 
       y="Count")+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  theme_bw()+
  scale_fill_brewer(palette = "Blues")+
  guides(fill=FALSE)
```


```{r }
# Industry is messy... it has > 1000 different industries  
ask_a_manager_2021_cleaned %>% 
  count(industry, sort=TRUE) %>% 
  mutate(percent = 100* n/sum(n)) %>% 
  filter(n>=500) %>% 
  ggplot(aes(x=fct_reorder(industry,n,.desc = TRUE),y= n,fill=industry))+
  geom_col()+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
    labs(x="Industry", 
       y="Count",
       title="Industries with >500 repondents")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))+
  guides(fill=FALSE)
```


```{r }
# Most of 'currency' is USD
ask_a_manager_2021_cleaned %>% 
  count(currency, sort=TRUE) %>% 
  mutate(percent = 100* n/sum(n)) %>% 
  ggplot(aes(x=fct_reorder(currency,n,.desc=TRUE),y= n,fill=currency))+
  geom_col()+
  labs(x="Currency Paid", 
       y="Count")+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  theme_bw()+
  guides(fill=FALSE)
```


```{r }
# 'country' 
ask_a_manager_2021_cleaned %>% 
  count(country, sort=TRUE) %>% 
  top_n(10) %>% 
  ggplot(aes(y=fct_reorder(country,n),x= n))+
  geom_col()+
  theme_bw()+
  labs(x="Count", 
       y="Country")+
  NULL
# use countrycode::countryname() to clean country names
```


```{r }
# 'city' 
ask_a_manager_2021_cleaned %>% 
  count(city, sort=TRUE) %>% 
  # mutate(percent = 100* n/sum(n)) %>% 
  top_n(15) %>% 
  ggplot(aes(y=fct_reorder(city,n),x= n))+
  geom_col()+
  theme_bw()+
  labs(x="Count", 
       y="City")+
  NULL
```


```{r }
# education
ask_a_manager_2021_cleaned %>% 
  filter(!is.na(education_level)) %>% 
  count(education_level) %>% 
  ggplot(aes(x=education_level,y= n,fill=education_level))+
  geom_col()+
  theme_bw()+
  labs(x= "Education level",y="Count")+
  scale_fill_brewer(palette = "Blues")+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  guides(fill=FALSE)+
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))

```


```{r }
# gender
ask_a_manager_2021_cleaned %>% 
  filter(gender %in% c("Woman","Man","Non-binary")) %>% 
  count(gender) %>% 
  ggplot(aes(x=fct_reorder(gender,n,.desc=TRUE),y = n,fill=gender))+
  geom_col()+
  theme_bw()+
  scale_fill_brewer(palette = "Blues")+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  guides(fill=FALSE)+
  labs(x="Gender",y="Count")+
  NULL
```


```{r }
# race
ask_a_manager_2021_cleaned %>% 
  filter(!is.na(race)) %>% 
  count(race) %>% 
  ggplot(aes(x=fct_reorder(race,n,.desc=TRUE),y= n,fill=race))+
  geom_col()+
  theme_bw()+
  labs(x= "Race",y="Count")+
  scale_fill_brewer(palette = "Blues")+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  guides(fill=FALSE)+
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))

```


```{r }
# overall_years_of_professional_experience 
ask_a_manager_2021_cleaned %>% 
  count(overall_experience ) %>% 
  ggplot(aes(x=overall_experience,y = n))+
  geom_col()+
  theme_bw()+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))

```


```{r }
# years_of_experience_in_field  
ask_a_manager_2021_cleaned %>% 
  count(field_experience  ) %>% 
  ggplot(aes(x=field_experience,y = n))+
  geom_col()+
  theme_bw()+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))

```
After viewing the data distribution in survey level, let's dig into salary in US.

```{r}
#delete country and rename country value as iso3, filter USA
us_data <-
  ask_a_manager_2021_cleaned %>% 
  select(-country) %>% 
  filter(iso3c== "USA")

us_data <- us_data %>%
  mutate(
    log_salary = log(annual_salary)
    ) %>% 
  drop_na()
```


```{r, fig.width=12}
us_data %>% 
  group_by(gender) %>% 
  summarize(
    mean_salary = mean(annual_salary)
  ) %>% 
  
  ggplot(aes(x = reorder(gender, -mean_salary), y = mean_salary)) +
  geom_col()
```


```{r}
#Cleaning the race variable
us_data <- us_data %>% 
  mutate(
    race_cleaned = case_when(
      race %in% c('Asian or Asian American', 'Asian or Asian American, White') ~ 'Asian or Asian American',
      race %in% c('Black or African American', 'Black or African American, White') ~ 'Black or African American',
      race %in% c('Hispanic, Latino, or Spanish origin', 'Hispanic, Latino, or Spanish origin, White') ~ 'Hispanic, Latino, or Spanish origin',
      race == "Another option not listed here or prefer not to answer" ~ "Others/Prefer not to say",
      TRUE ~ race
    )
  )
```

```{r, fig.width=12}
us_data %>% 
  group_by(race_cleaned) %>% 
  summarize(
    mean_salary = mean(annual_salary)
  ) %>% 
  
  ggplot(aes(x = reorder(race_cleaned, -mean_salary), y = mean_salary)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))
```


```{r, fig.width=12}
top_industries <- us_data %>% 
  group_by(industry) %>% 
  count(sort = TRUE) %>% 
  head(10) %>% 
  select(industry) %>% 
  pull()


us_data %>%
  filter(industry %in% top_industries) %>% 
  group_by(industry) %>% 
  summarize(
    mean_salary = mean(annual_salary)
  ) %>% 
  
  ggplot(aes(x = reorder(industry, -mean_salary), y = mean_salary)) +
  geom_col() +
 theme(axis.text.x = element_text(angle = 45, vjust = 0.5))
```


```{r, fig.width = 12}
us_data %>%
  group_by(overall_experience) %>% 
  summarize(
    mean_salary = mean(annual_salary)
  ) %>% 
  
  ggplot(aes(x = overall_experience, y = mean_salary)) +
  geom_col()
```

```{r, fig.width = 12}
us_data %>%
  group_by(age) %>% 
  summarize(
    mean_salary = mean(annual_salary)
  ) %>% 
  
  ggplot(aes(x = age, y = mean_salary)) +
  geom_col()
```


```{r, fig.width = 12}
us_data %>%
  group_by(field_experience) %>% 
  summarize(
    mean_salary = mean(annual_salary)
  ) %>% 
  
  ggplot(aes(x = field_experience, y = mean_salary)) +
  geom_col()
```


```{r, fig.width = 12}
us_data %>%
  group_by(education_level) %>% 
  summarize(
    mean_salary = mean(annual_salary)
  ) %>% 
  
  ggplot(aes(x = education_level, y = mean_salary)) +
  geom_col()
```


